sudo: required

env:
  - distribution: ubuntu
  - distribution: fedora
  - distribution: arch
  - distribution: debian-testing
  - distribution: debian

services:
  - docker

jobs:
  include:
    - stage: update system
      script:
        - ./ci/update_ci.sh
    - stage: build
      script:
        - script=compile CXX=clang++ CC=clang ./ci/execute.sh
      script:
        - script=compile CXX=g++ CC=gcc ./ci/execute.sh
        - script=static_analysis ./ci/execute.sh
        - script=compile make_command="broadwayd & CTEST_OUTPUT_ON_FAILURE=1 make test" ./ci/execute.sh

