sudo: required

env:
  - distribution=ubuntu CXX=clang++ CC=clang
  - distribution=ubuntu CXX=g++ CC=gcc
  - distribution=fedora CXX=clang++ CC=clang
  - distribution=fedora CXX=g++ CC=gcc
  - distribution=arch CXX=clang++ CC=clang
  - distribution=arch CXX=g++ CC=gcc
  - distribution=debian-testing CXX=clang++ CC=clang
  - distribution=debian-testing CXX=g++ CC=gcc
  - distribution=debian CXX=clang++ CC=clang
  - distribution=debian CXX=g++ CC=gcc

services:
  - docker

before_script:
  - docker pull "cppit/jucipp:${distribution}"

script:
  - script=compile ./ci/execute.sh
  - script=static_analysis ./ci/execute.sh
  - script=compile make_command="broadwayd & CTEST_OUTPUT_ON_FAILURE=1 make test" ./ci/execute.sh
